service: nest-serverless-lambda-demo

plugins:
  - serverless-dotenv-plugin
  - 'serverless-plugin-typescript'
  - serverless-plugin-optimize
  - serverless-offline

useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  environment:
    DATABASE_URL: ${env:DATABASE_URL}

functions:
  main:
    handler: src/lambda.handler
    events:
      - http:
          method: any
          path: /{any+}
